### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by connorourke**
MPI and pool version, with an example run script for Balena. 

Could do with a tidy, but have play with it anyway. I haven't created a branch for the version that writes out a script to do the spawning, this one runs better and can still more or less be run in the same way as the old script.

### CODE REVIEW

**Comment by bjmorgan** [comment]
Looks great (& complicated). Can you write a README that explains how to use the MPI and pool versions?

**Comment by connorourke** [comment]
Yep - I'll stick one in Monday Morning. There is a error in the example run script and another bug - just testing the fix. I'll commit it Monday too, assuming it fixes the problem.

**Comment by bjmorgan** [comment]
It would be nice to have unit tests for this, even if at this stage they just test against the bugs you have come up against when testing.

**Comment by connorourke** [comment]
Bugs fixed. No README - but the options file and example run_scripts should now make it clear what you need to run mpi/pool/serial versions. I'll sort out unit tests, and a README next.

**Pull request merged**
